"""add source event id to notifications

Revision ID: 1fd3b3ba963e
Revises: 2163f5accd8d
Create Date: 2026-10-09 16:58:28.704776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd3b3ba963e'
down_revision: Union[str, Sequence[str], None] = '2163f5accd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('source_event_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_notifications_source_event_id', 'notifications', ['source_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_notifications_source_event_id', 'notifications', type_='unique')
    op.drop_column('notifications', 'source_event_id')
    # ### end Alembic commands ###
