"""deduplicate notifications by event and recipient

Revision ID: 6d3a696997f2
Revises: 1fd3b3ba963e
Create Date: 2026-10-09 17:30:47.441474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3a696997f2'
down_revision: Union[str, Sequence[str], None] = '1fd3b3ba963e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_notifications_source_event_id'), 'notifications', type_='unique')
    op.create_unique_constraint('uq_notifications_source_event_id', 'notifications', ['source_event_id', 'recipient'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_notifications_source_event_id', 'notifications', type_='unique')
    op.create_unique_constraint(op.f('uq_notifications_source_event_id'), 'notifications', ['source_event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
